### ISSUE TITLE
Missing Stylesheet error

### ISSUE THREAD

**Issue by aduffett** [thirdwunder/TW-LP-Boilerplate#1]
Good day. I get the following message at the bottom of my theme page in the admin section. 
>"The following themes are installed but incomplete. Themes must have a stylesheet and a template.

>Name	Description	
>TW-LP-Boilerplate-master	Stylesheet is missing."

I have tried changing the address, as well as the call for the file. 
`<link rel="stylesheet" href="<?php echo $path; ?>assets/css/style.css" />`
to
`  <link rel="stylesheet" href="<?php echo get_template_directory_uri(); ?>assets/css/style.css">`

All without any luck.

**Comment by mohamedhamad** [comment]
Hi aduffett,
so this boiler plate is actually for use with the Inboundnow.com landing page plugin.
its a boilerplate landing page template for the plugin.

are you trying to use it as a theme?

**Comment by mohamedhamad** [comment]
I would suggest you try my wordpress boilerplate theme, https://github.com/thirdwunder/TW-WP-BS-Boilerplate

**Comment by aduffett** [comment]
Oh!

Yes I was looking for WP theme. Many thanks, and sorry for the mix up.
